# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class GetEventData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_types: List[str] = Field(
        ...,
        description="Specify the event type(s) to analyze (optional). Leave this section empty to analyze all event types.",
        title="Event Types",
    )
    event_columns: List[str] = Field(
        ..., description="The interested event columns", title="Event Columns"
    )
    include_display_values: Optional[bool] = Field(
        True,
        description="Whether or not to include display values for event types",
        title="Include Display Values",
    )


class CustomizeColumns(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    drop_columns: Optional[List[str]] = Field(
        [], description="List of columns to drop.", title="Drop Columns"
    )
    retain_columns: Optional[List[str]] = Field(
        [],
        description='List of columns to retain with the order specified by the list.\n                        "Keep all the columns if the list is empty.',
        title="Retain Columns",
    )
    rename_columns: Optional[Dict[str, str]] = Field(
        {}, description="Dictionary of columns to rename.", title="Rename Columns"
    )


class SqlQuery(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    query: Optional[str] = Field(
        "",
        description="SQL query string to apply to the DataFrame. Use 'df' as the table name in the query.",
        title="Query",
    )


class Filetype(str, Enum):
    csv = "csv"
    gpkg = "gpkg"
    geoparquet = "geoparquet"


class PersistEvents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filename: Optional[str] = Field(
        None,
        description="            Optional filename to persist text to within the `root_path`.\n            If not provided, a filename will be generated based on a hash of the df content.\n            ",
        title="Filename",
    )
    filetypes: Optional[List[Filetype]] = Field(
        ["csv"], description="The output format", title="Filetypes"
    )
    sanitize: Optional[bool] = Field(
        True,
        description="Whether to sanitize the dataframe for Arrow compatibility before persisting, recommended when including event or observation details",
        title="Sanitize",
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TemporalGrouper(RootModel[str]):
    root: str = Field(..., title="Time")


class ValueGrouper(RootModel[str]):
    root: str = Field(..., title="Category")


class BoundingBox(BaseModel):
    min_y: Optional[float] = Field(-90.0, title="Min Latitude")
    max_y: Optional[float] = Field(90.0, title="Max Latitude")
    min_x: Optional[float] = Field(-180.0, title="Min Longitude")
    max_x: Optional[float] = Field(180.0, title="Max Longitude")


class Coordinate(BaseModel):
    y: float = Field(..., description="Example -0.15293", title="Latitude")
    x: float = Field(..., description="Example 37.30906", title="Longitude")


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper]]] = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class FilterEvents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bounding_box: Optional[BoundingBox] = Field(
        default_factory=lambda: BoundingBox.model_validate(
            {"min_y": -90.0, "max_y": 90.0, "min_x": -180.0, "max_x": 180.0}
        ),
        description="Filter events to inside these bounding coordinates.",
        title="Bounding Box",
    )
    filter_point_coords: Optional[List[Coordinate]] = Field(
        [],
        description="By adding a filter, the workflow will not include events recorded at the specified coordinates.",
        title="Filter Exact Point Coordinates",
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    er_client_name: Optional[ErClientName] = Field(None, title="Data Source")
    get_event_data: Optional[GetEventData] = Field(None, title="Get Event Data")
    groupers: Optional[Groupers] = Field(None, title="Group Data")
    filter_events: Optional[FilterEvents] = Field(
        None, title="Filter Event Relocations"
    )
    customize_columns: Optional[CustomizeColumns] = Field(None, title="Process Columns")
    sql_query: Optional[SqlQuery] = Field(None, title="Apply SQL Query")
    persist_events: Optional[PersistEvents] = Field(None, title="Persist Events")
