# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class SubjectObs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject_group_name: str = Field(
        ...,
        description="⚠️ The use of a group with mixed subtypes could lead to unexpected results",
        title="Subject Group Name",
    )


class FilteredWeatherStation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    values: Optional[List[str]] = Field(
        None,
        description="The values to keep. If None, no filtering is applied.",
        title="Values",
    )


class DfWithTemporalIndex(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cast_to_datetime: Optional[bool] = Field(
        True,
        description="Whether to attempt casting `time_col` to datetime.",
        title="Cast To Datetime",
    )
    format: Optional[str] = Field(
        "mixed",
        description='            If `cast_to_datetime=True`, the format to pass to `pd.to_datetime`\n            when attempting to cast `time_col` to datetime. Defaults to "mixed".\n            ',
        title="Format",
    )


class Filetype(str, Enum):
    csv = "csv"
    gpkg = "gpkg"
    geoparquet = "geoparquet"


class PersistObservations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filename: Optional[str] = Field(
        None,
        description="            Optional filename to persist text to within the `root_path`.\n            If not provided, a filename will be generated based on a hash of the df content.\n            ",
        title="Filename",
    )
    filetypes: Optional[List[Filetype]] = Field(
        ["csv"], description="The output format", title="Filetypes"
    )
    sanitize: Optional[bool] = Field(
        False,
        description="Whether to sanitize the dataframe for Arrow compatibility before persisting, recommended when including event or observation details",
        title="Sanitize",
    )


class PersistDailySummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filename: Optional[str] = Field(
        None,
        description="            Optional filename to persist text to within the `root_path`.\n            If not provided, a filename will be generated based on a hash of the df content.\n            ",
        title="Filename",
    )
    filetypes: Optional[List[Filetype]] = Field(
        ["csv"], description="The output format", title="Filetypes"
    )
    sanitize: Optional[bool] = Field(
        False,
        description="Whether to sanitize the dataframe for Arrow compatibility before persisting, recommended when including event or observation details",
        title="Sanitize",
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TemporalGrouper(RootModel[str]):
    root: str = Field(..., title="Time")


class ValueGrouper(RootModel[str]):
    root: str = Field(..., title="Category")


class LineStyle(BaseModel):
    color: Optional[str] = Field(None, title="Color")
    dash: Optional[str] = Field(None, title="Dash")
    shape: Optional[str] = Field(None, title="Shape")


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper]]] = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class PrecipitationChart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    line_kwargs: Optional[LineStyle] = Field(
        None, description="Line style settings", title="Line Kwargs"
    )


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    er_client_name: Optional[ErClientName] = Field(
        None, title="Select EarthRanger Data Source"
    )
    subject_obs: Optional[SubjectObs] = Field(
        None, title="Get Subject Group Observations from EarthRanger"
    )
    filtered_weather_station: Optional[FilteredWeatherStation] = Field(
        None, title="Select Weather Stations"
    )
    groupers: Optional[Groupers] = Field(None, title="Set Groupers")
    df_with_temporal_index: Optional[DfWithTemporalIndex] = Field(
        None, title="Add temporal index"
    )
    persist_observations: Optional[PersistObservations] = Field(
        None, title="Persist Observations"
    )
    persist_daily_summary: Optional[PersistDailySummary] = Field(
        None, title="Persist Daily Summary"
    )
    precipitation_chart: Optional[PrecipitationChart] = Field(
        None, title="Draw Precipitation Chart"
    )
