workflow_details:
  name: "Patrol Events Workflow"
  description: "Process and visualize patrol observations and events."

er_client_name:
  data_source:
    name: "mara_ep"
    server: "server_name"
    username: "username"
    password: "password"

er_patrol_types:
  patrol_types: [ "patrol_type"
    ]

er_patrol_status:
  status: ["done"]

fetch_patrol_events:
    event_type: []
    drop_null_geometry: false
time_range:
  since: "2024-01-01T00:00:00Z"
  until: "2024-12-31T23:59:59Z"

groupers:
  groupers:
    - "%B"

base_map_defs:
  base_maps:
    - url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
      opacity: 0.1
    - url: "https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places_Alternate/MapServer/tile/{z}/{y}/{x}"
      opacity: 0.8
      max_zoom: 17